# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-28 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multi_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_name', models.CharField(max_length=50, verbose_name='歌名')),
                ('multi_src', models.CharField(max_length=150, verbose_name='链接')),
                ('multi_s', models.CharField(max_length=10, verbose_name='歌手')),
                ('nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('music_type', models.IntegerField(choices=[('popular', '流行'), ('Recommend', '站长推荐'), ('cure', '治愈'), ('rock', '摇滚'), ('Light_music', '轻音乐')], max_length=20, verbose_name='音乐类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('image', models.ImageField(default='image/music.jpg', upload_to='imgage/%Y/%m')),
            ],
            options={
                'verbose_name': '主页歌曲',
                'verbose_name_plural': '主页歌曲',
            },
        ),
    ]
