# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi_m',
            name='music_type',
            field=models.CharField(choices=[('popular', '流行'), ('Recommend', '站长推荐'), ('cure', '治愈'), ('rock', '摇滚'), ('Light_music', '轻音乐')], max_length=20, verbose_name='音乐类型'),
        ),
    ]
