# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi_m',
            name='music_type',
            field=models.CharField(choices=[('popular', '流行'), ('Recommend', '歌友收藏'), ('cure', '治愈'), ('rock', '摇滚')], max_length=20, verbose_name='音乐类型'),
        ),
    ]
