# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-05 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': '验证码', 'verbose_name_plural': '验证码'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='默认昵称', max_length=50, verbose_name='昵称'),
        ),
    ]
