# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-06 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190305_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updata_pwd',
            field=models.CharField(default='', max_length=200, verbose_name='更新暂存密码'),
        ),
    ]
