# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-20 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_updata_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='updata_pwd',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='更新暂存密码'),
        ),
    ]
